# @include removeClassByMask.coffee
# @include removeAttrByMask.coffee
# @include snapshotStyles.coffee
# @include vendorPrefix.coffee
# @include tagName.coffee
# @include findFirst.coffee
# @include truth.coffee
# @include hasAttr.coffee
# @include ajax.coffee
